parameters:
- name: environmentName
  type: string
  default: ''

jobs:
- job: Tag_Work_Items
  displayName: 'Tag work items: ${{ parameters.environmentName }}'
  pool:
    vmImage: ubuntu-latest

  steps:
  - task: PowerShell@2
    displayName: 'Update Azure DevOps Work Item Tags'
    inputs:
      targetType: 'inline'
      script: |
        # =========================================================
        # Configuration / Inputs
        # =========================================================
        $org     = "$(ADO_ORG)"              # Azure DevOps organization
        $project = "$(ADO_PROJECT)"          # Azure DevOps project
        $envTag  = "DevOpsDeployed:${{ parameters.environmentName }}"  # New environment tag

        Write-Host "=========================================="
        Write-Host "Azure DevOps Work Item Tag Update"
        Write-Host "=========================================="
        Write-Host "Organization : $org"
        Write-Host "Project      : $project"
        Write-Host "Environment  : $envTag"

        # =========================================================
        # Validate PAT
        # =========================================================
        $pat = "$(ADO_PAT)"
        if ([string]::IsNullOrWhiteSpace($pat)) {
          throw "ADO_PAT is missing. Please check variable group 'workitem-tagging-secrets'."
        }

        # =========================================================
        # Build Authorization Header (Basic Auth)
        # =========================================================
        $basicAuth = [Convert]::ToBase64String(
          [Text.Encoding]::ASCII.GetBytes(":$pat")
        )

        # =========================================================
        # Extract Work Item IDs from Commit Message (AB#1234)
        # =========================================================
        $commitMsg = "$(Build.SourceVersionMessage)"
        Write-Host "Commit Message: $commitMsg"

        $ids = [regex]::Matches($commitMsg, 'AB#(\d+)') |
               ForEach-Object { $_.Groups[1].Value } |
               Select-Object -Unique

        Write-Host "Work Item IDs found: $($ids -join ', ')"

        if ($ids.Count -eq 0) {
          Write-Host "No linked work items found. Exiting."
          exit 0
        }

        # =========================================================
        # Counters for summary
        # =========================================================
        $successCount = 0
        $failureCount = 0

        # =========================================================
        # Process Each Work Item
        # =========================================================
        foreach ($id in $ids) {

          Write-Host ""
          Write-Host "------------------------------------------"
          Write-Host "Processing Work Item ID: $id"
          Write-Host "------------------------------------------"

          try {
            # -----------------------------------------------------
            # Work Item API URL
            # -----------------------------------------------------
            $url = "https://dev.azure.com/$org/$project/_apis/wit/workitems/$id?api-version=7.1-preview.3"

            # -----------------------------------------------------
            # Get Existing Work Item
            # -----------------------------------------------------
            $wi = Invoke-RestMethod -Method Get -Uri $url -Headers @{
              Authorization = "Basic $basicAuth"
            }

            $wiTitle      = $wi.fields.'System.Title'
            $existingTags = $wi.fields.'System.Tags'
            if (-not $existingTags) { $existingTags = "" }

            Write-Host "Title         : $wiTitle"
            Write-Host "Existing Tags : '$existingTags'"

            # -----------------------------------------------------
            # Split existing tags into array
            # -----------------------------------------------------
            $tagList = @()
            if (-not [string]::IsNullOrWhiteSpace($existingTags)) {
              $tagList = $existingTags -split ';' | ForEach-Object { $_.Trim() }
            }

            # -----------------------------------------------------
            # Skip if same DevOpsDeployed tag already exists
            # -----------------------------------------------------
            if ($tagList -contains $envTag) {
              Write-Host "Already tagged with $envTag. Skipping."
              $successCount++
              continue
            }

            # -----------------------------------------------------
            # Remove ALL existing DevOpsDeployed:* tags
            # -----------------------------------------------------
            $filteredTags = $tagList | Where-Object { $_ -notmatch '^DevOpsDeployed:' }

            # -----------------------------------------------------
            # Add new environment tag
            # -----------------------------------------------------
            $filteredTags += $envTag

            # -----------------------------------------------------
            # Rebuild tag string
            # -----------------------------------------------------
            $newTags = $filteredTags -join '; '

            Write-Host "Updated Tags  : '$newTags'"

            # -----------------------------------------------------
            # Create PATCH payload
            # -----------------------------------------------------
            $patchDocument = '[{"op":"replace","path":"/fields/System.Tags","value":"' + $newTags + '"}]'

            # -----------------------------------------------------
            # Update Work Item
            # -----------------------------------------------------
            Invoke-RestMethod -Method Patch -Uri $url -Headers @{
              Authorization  = "Basic $basicAuth"
              "Content-Type" = "application/json-patch+json"
            } -Body $patchDocument

            Write-Host "Work Item $id updated successfully"
            $successCount++

          }
          catch {
            Write-Host "Error updating Work Item $id"
            Write-Host "Error: $($_.Exception.Message)"
            $failureCount++
          }
        }

        # =========================================================
        # Final Summary
        # =========================================================
        Write-Host ""
        Write-Host "=========================================="
        Write-Host "Update Summary"
        Write-Host "=========================================="
        Write-Host "Successfully updated : $successCount"
        Write-Host "Failed              : $failureCount"
        Write-Host "Total processed     : $($ids.Count)"
        Write-Host "=========================================="

        if ($failureCount -gt 0) {
          Write-Host "##vso[task.logissue type=warning]Some work items failed to update"
        }
