parameters:
- name: environmentName
  type: string
  default: 'BUILD'

jobs:
- job: Tag_Work_Items
  displayName: 'Tag work items: ${{ parameters.environmentName }}'
  pool:
    vmImage: ubuntu-latest

  steps:
  - powershell: |
      $org = "$(ADO_ORG)"
      $project = "$(ADO_PROJECT)"
      $envTag = "DevOpsDeployed:${{ parameters.environmentName }}"
      
      Write-Host "Environment: ${{ parameters.environmentName }}"
      Write-Host "Tag: $envTag"
      Write-Host "Org: $org"
      Write-Host "Project: $project"

      $pat = "$(ADO_PAT)"
      if ([string]::IsNullOrWhiteSpace($pat)) {
        throw "ADO_PAT is missing"
      }

      # Auth header
      $basicAuth = [Convert]::ToBase64String([Text.Encoding]::ASCII.GetBytes(":$pat"))

      # Extract Work Item IDs
      $commitMsg = "$(Build.SourceVersionMessage)"
      Write-Host "Commit: $commitMsg"
      
      $ids = [regex]::Matches($commitMsg, 'AB#(\d+)') |
             ForEach-Object { $_.Groups[1].Value } |
             Select-Object -Unique

      Write-Host "Found IDs: $($ids -join ', ')"

      if ($ids.Count -eq 0) {
        Write-Host "No work items found"
        exit 0
      }

      foreach ($id in $ids) {
        Write-Host ""
        Write-Host "Processing ID: $id"
        
        $url = "https://dev.azure.com/$org/$project/_apis/wit/workitems/$($id)?api-version=7.1-preview.3"
        
        try {
          # Get current work item
          $wi = Invoke-RestMethod -Method Get -Uri $url -Headers @{
            Authorization = "Basic $basicAuth"
          }

          $title = $wi.fields.'System.Title'
          $currentTags = $wi.fields.'System.Tags'
          if (-not $currentTags) { $currentTags = "" }

          Write-Host "Title: $title"
          Write-Host "Current Tags: $currentTags"
          
          # Check if tag already exists
          if ($currentTags -match [regex]::Escape($envTag)) { 
            Write-Host "Already has tag: $envTag"
            continue 
          }

          # Build new tags
          if ([string]::IsNullOrWhiteSpace($currentTags)) {
            $newTags = $envTag
          } else {
            $newTags = "$currentTags; $envTag"
          }

          Write-Host "New Tags: $newTags"

          # CORRECT JSON FORMAT for Azure DevOps PATCH
          # This is the key fix - using proper JSON array format
          $patchDocument = @"
[
  {
    "op": "replace",
    "path": "/fields/System.Tags",
    "value": "$newTags"
  }
]
"@

          Write-Host "Patch Document: $patchDocument"
          
          # Update work item
          $response = Invoke-RestMethod -Method Patch -Uri $url -Headers @{
            Authorization  = "Basic $basicAuth"
            "Content-Type" = "application/json-patch+json"
          } -Body $patchDocument
          
          Write-Host "✅ Updated: $title"
          Write-Host "   New Tags: $($response.fields.'System.Tags')"
          
        } catch {
          Write-Host "❌ Error: $($_.Exception.Message)"
          
          # Alternative method - try different JSON format
          Write-Host "Trying alternative JSON format..."
          
          try {
            # Alternative: Use hashtable and ConvertTo-Json
            $patchData = @(
              @{
                op = "replace"
                path = "/fields/System.Tags"
                value = $newTags
              }
            )
            
            $body = $patchData | ConvertTo-Json -Compress
            Write-Host "Alternative Body: $body"
            
            $response = Invoke-RestMethod -Method Patch -Uri $url -Headers @{
              Authorization  = "Basic $basicAuth"
              "Content-Type" = "application/json-patch+json"
            } -Body $body
            
            Write-Host "✅ Updated with alternative format"
            
          } catch {
            Write-Host "❌ Both methods failed"
          }
        }
      }
    displayName: 'Update Azure DevOps Work Item Tags'